function ListGroup() {
  return (
    <ul className="list-group">
      <li className="list-group-item">Cras justo odio</li>
      <li className="list-group-item">Dapibus ac facilisis in</li>
      <li className="list-group-item">Morbi leo risus</li>
      <li className="list-group-item">Porta ac consectetur ac</li>
      <li className="list-group-item">Vestibulum at eros</li>
    </ul>
  );
}

export default ListGroup;

// Firstly we install bootstrap using npm install bootstrap@5.2.3 to give our app a modern looking
// feel. Then import it in one of our CSS files e.g. App.css which contains all styles for our app
//  component, and we dont need them so delete them. We also have index.css, where we have global
//  styles for our application, and we dont need any of these styles because they were generated by
//  vite. Now go to main.tsx and we can see that our index.css file was imported here, we are going
//  to replace this line with import ‘bootstrap/dist/css/bootstrap.css’. 

// Next create a new folder in the src folder callled components. And inside it create a file
//  called ListGroup.tsx. In the file we will declare a function called ListGroup and inside it
//   we will return an Unordered List  with class attribute set to “list-group” and within this 
//   Unordered List we have multiple list items with class attribute set to “list-group-items”. 
//   Class is a reserved keyword in JS we can use it, so we change into className Then we need to 
//   export default ListGorup component. Then go to App.tsx and import ListGorup component. And then 
//   inside the App component/ function inside the div we will use the ListGroup as an element. 

// Note that prettier marked our JSX markup in parentheses e.g. after the return keyword, so that 
// the markup could be broken down the markup in multiple lines. 